In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("hr_data.csv")
data

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [3]:
sales_left = data[(data['department'] == 'sales') & (data['left'] == 1)]
sales_left

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14967,87507,2,128,3,0,1,0,sales,low
14968,87518,2,128,3,0,1,0,sales,medium
14969,87520,2,157,3,0,1,0,sales,medium
14970,87530,4,225,5,0,1,0,sales,medium
14971,87533,2,140,3,0,1,0,sales,medium

# distribution of sal based on department

In [14]:
data.pivot_table(values=['salary'],
                index=['department'],
                aggfunc=['count'])

             count
            salary
department
IT            1227
RandD          787
accounting     767
hr             739
management     630
marketing      858
product_mng    902
sales         4140
support       2229
technical     2720

In [17]:
data.pivot_table(index='department',aggfunc='count')

,Work_accident,average_montly_hours,employee_id,left,number_project,promotion_last_5years,salary,time_spend_company
department,,,,,,,,
IT,1227,1227,1227,1227,1227,1227,1227,1227
RandD,787,787,787,787,787,787,787,787
accounting,767,767,767,767,767,767,767,767
hr,739,739,739,739,739,739,739,739
management,630,630,630,630,630,630,630,630
marketing,858,858,858,858,858,858,858,858
product_mng,902,902,902,902,902,902,902,902
sales,4140,4140,4140,4140,4140,4140,4140,4140
support,2229,2229,2229,2229,2229,2229,2229,2229
technical,2720,2720,2720,2720,2720,2720,2720,2720

In [19]:
data.pivot_table(index='department',aggfunc='sum')

,Work_accident,average_montly_hours,employee_id,left,number_project,promotion_last_5years,salary,time_spend_company
department,,,,,,,,
IT,164,248119,56344929,273,4683,3,mediummediummediummediummediummediumlowlowlowl...,4256
RandD,134,158030,32948168,121,3033,27,mediummediummediummediummediummediummediummedi...,2650
accounting,96,154292,34474313,204,2934,14,lowlowlowlowmediummediummediumlowmediummediumm...,2702
hr,89,146828,31664725,215,2701,15,lowlowlowlowmediummediummediumhighmediummedium...,2480
management,103,126787,33597098,91,2432,69,mediumlowlowlowlowlowlowmediumlowmediumlowlowl...,2711
marketing,138,171073,40715777,203,3164,43,mediumlowlowlowlowlowlowlowlowlowlowlowlowlowl...,3063
product_mng,132,180369,44016858,198,3434,0,mediummediummediummediummediumhighlowmediummed...,3135
sales,587,831773,192072490,1014,15634,100,lowmediummediumlowlowlowlowlowlowlowlowlowlowl...,14631
support,345,447490,97874011,555,8479,20,lowlowlowlowlowlowlowlowlowlowlowlowlowlowlowl...,7563
technical,381,550793,117615620,697,10548,28,lowlowlowlowlowlowlowlowlowlowlowlowlowlowlowl...,9279

In [25]:
# we can use more than one functions in aggfunc
data.pivot_table(values='number_project',index='department',aggfunc=['count','sum'])

                     count            sum
            number_project number_project
department
IT                    1227           4683
RandD                  787           3033
accounting             767           2934
hr                     739           2701
management             630           2432
marketing              858           3164
product_mng            902           3434
sales                 4140          15634
support               2229           8479
technical             2720          10548

In [31]:
#avg monthly hours based on department
data.pivot_table(values='average_montly_hours',index='department',aggfunc='mean')

             average_montly_hours
department
IT                     202.215974
RandD                  200.800508
accounting             201.162973
hr                     198.684709
management             201.249206
marketing              199.385781
product_mng            199.965632
sales                  200.911353
support                200.758188
technical              202.497426

In [35]:
# promotion last 5 year based sal
data.pivot_table(values='promotion_last_5years',index='salary',aggfunc='count')

        promotion_last_5years
salary
high                     1237
low                      7316
medium                   6446