# Pivot Table

* In the case of groupby function we can only apply single aggregate function but using pivot table we can apply multiple aggregate functionon the column
* Syntax ---->  df.pivot_table()

In [3]:
import pandas as pd
data=pd.read_csv("titanic.csv") 
data

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [7]:
data.pivot_table(values=['survived'],
                index=['sex'],
                aggfunc=['sum'])

            sum
       survived
sex
female      339
male        161

In [9]:
data.pivot_table(values=['age'],
                index=['sex'],
                aggfunc=['mean'])

             mean
              age
sex
female  28.687071
male    30.585233

In [11]:
data.pivot_table(values=['sex'],
                index=['survived'],
                aggfunc=['count'])

         count
           sex
survived
0          809
1          500

In [13]:
data.pivot_table(values=['fare'],
                index=['pclass'],
                aggfunc=['sum'])

               sum
              fare
pclass
1       28265.4043
2        5866.6374
3        9418.4452

# joins

* To store data related to multiple tables into a single table
* to fetch data from multiple tables simultaneously, we will go with joins

* Types :- 1) left
           2) right
           3) inner
           4) outer

In [17]:
department=pd.DataFrame({
    'departmentId' : ['1','2','3','4'],
    'departmentName' : ['accounting','research','sales','operations'],
    'loc' : ['new york','dallas','chicago','boston']
})
department

  departmentId departmentName       loc
0            1     accounting  new york
1            2       research    dallas
2            3          sales   chicago
3            4     operations    boston

In [ ]:
employee=pd.DataFrame({
    'empno' : ['1','2','3','4'],
    'departmentName' : ['accounting','research','sales','operations'],
    'loc' : ['new york','dallas','chicago','boston']
})
department

* Syntax----> pd.merge(df1,df2,df3,......,dfn,on=commoncolumn,how=[left,right,inner,outer])
* Bydefault how will perform inner join