In [2]:
import pandas as pd
df=pd.read_csv("zomato_cleaned_data.csv")
df

,Unnamed: 0,name,online_order,book_table,rate,votes,location,rest_type,cuisines,costfor2,type
0,0,Jalsa,Yes,Yes,4.100000,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet
1,1,Spice Elephant,Yes,No,4.100000,787,Banashankari,Casual Dining,others,800,Buffet
2,2,San Churro Cafe,Yes,No,3.800000,918,Banashankari,others,others,800,Buffet
3,3,Addhuri Udupi Bhojana,No,No,3.700000,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet
4,4,Grand Village,No,No,3.800000,166,Basavanagudi,Casual Dining,others,600,Buffet
...,...,...,...,...,...,...,...,...,...,...,...
51037,51604,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.600000,27,Whitefield,others,Continental,1500,Pubs and bars
51038,51605,Vinod Bar And Restaurant,No,No,3.700142,0,Whitefield,others,Finger Food,600,Pubs and bars
51039,51606,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,3.700142,0,Whitefield,others,Finger Food,2000,Pubs and bars
51040,51607,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.300000,236,others,others,Finger Food,2500,Pubs and bars
51041,51608,The Nest - The Den Bengaluru,No,No,3.400000,13,others,others,others,1500,Pubs and bars

In [6]:
df.columns

Index(['Unnamed: 0', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'location', 'rest_type', 'cuisines', 'costfor2', 'type'],
      dtype='object')

-------------------------------------------------------------------------------
1. Create a pivot table to find the count of restaurants in 
each location.

In [10]:
a=df.pivot_table(index='location',values='rest_type',aggfunc='count')
a

                       rest_type
location
BTM                         5056
Banashankari                 902
Banaswadi                    640
Bannerghatta Road           1609
Basavanagudi                 684
Bellandur                   1268
Brigade Road                1210
Brookefield                  656
Church Street                566
Commercial Street            370
Cunningham Road              490
Domlur                       482
Ejipura                      433
Electronic City             1246
Frazer Town                  714
HSR                         2494
Indiranagar                 2026
JP Nagar                    2218
Jayanagar                   1916
Kalyan Nagar                 841
Kammanahalli                 639
Koramangala 1st Block       1236
Koramangala 4th Block       1017
Koramangala 5th Block       2479
Koramangala 6th Block       1127
Koramangala 7th Block       1174
Lavelle Road                 518
MG Road                      893
Malleshwaram                 721
Marathahalli                1805
New BEL Road                 644
Old Airport Road             437
Rajajinagar                  591
Residency Road               671
Richmond Road                803
Sarjapur Road               1047
Shanti Nagar                 508
Shivajinagar                 498
St. Marks Road               343
Ulsoor                      1011
Whitefield                  2105
others                      4954

-------------------------------------------------------------------------------
2.Find the average rate for each rest_type.

In [12]:
b=df.pivot_table(index='rest_type',values='rate',aggfunc='mean')
b

                        rate
rest_type
Bakery              3.643212
Cafe                3.835373
Casual Dining       3.737871
Casual Dining, Bar  4.063988
Delivery            3.616833
Dessert Parlor      3.846457
Quick Bites         3.587687
Takeaway, Delivery  3.581825
others              3.821901

--------------------------------------------------------------------------------
3. Create a pivot table showing the average cost for 2 
across different location and type combinations.

In [24]:
c=df.pivot_table(index=['location','type'],values='costfor2',aggfunc='mean')
c

                                costfor2
location type
BTM      Buffet              1038.095238
         Cafes                490.963855
         Delivery             385.492958
         Desserts             297.525253
         Dine-out             396.590361
...                                  ...
others   Delivery             421.254037
         Desserts             387.934783
         Dine-out             539.259498
         Drinks & nightlife  1504.666667
         Pubs and bars       1376.595745

[280 rows x 1 columns]

--------------------------------------------------------------------
4. Find the total votes received by each rest_type for each type (Buffet, Cafes, Delivery, etc.).

In [29]:
d=df.pivot_table(index='rest_type',columns='type',values='votes',aggfunc='sum')
d

type,Buffet,Cafes,Delivery,Desserts,Dine-out,Drinks & nightlife,Pubs and bars
rest_type,,,,,,,
Bakery,NaN,NaN,15792.0,18915.0,735.0,NaN,142.0
Cafe,0.0,459590.0,465537.0,57366.0,452520.0,32.0,323.0
Casual Dining,528222.0,366.0,2013430.0,39923.0,1941737.0,7234.0,0.0
"Casual Dining, Bar",147814.0,NaN,274009.0,NaN,393933.0,163059.0,230910.0
Delivery,NaN,21.0,210843.0,12693.0,45.0,NaN,23.0
Dessert Parlor,NaN,913.0,163076.0,151485.0,6378.0,NaN,364.0
Quick Bites,93.0,3237.0,829078.0,19901.0,620820.0,0.0,NaN
"Takeaway, Delivery",NaN,0.0,83316.0,3859.0,497.0,NaN,NaN
others,195397.0,357431.0,1181001.0,232796.0,1698803.0,1077039.0,461144.0

---------------------------------------------------------------------------------
5. Count how many restaurants accept online orders 
(online_order) across each location.

In [60]:
data=df[df['online_order']=='Yes']
data
data.pivot_table(index='location',values='name',aggfunc='count')

                       name
location
BTM                    3293
Banashankari            505
Banaswadi               338
Bannerghatta Road       924
Basavanagudi            441
Bellandur               751
Brigade Road            658
Brookefield             417
Church Street           340
Commercial Street       142
Cunningham Road         322
Domlur                  235
Ejipura                 219
Electronic City         570
Frazer Town             427
HSR                    1910
Indiranagar            1329
JP Nagar               1307
Jayanagar              1364
Kalyan Nagar            491
Kammanahalli            375
Koramangala 1st Block   852
Koramangala 4th Block   558
Koramangala 5th Block  1613
Koramangala 6th Block   682
Koramangala 7th Block   785
Lavelle Road            203
MG Road                 373
Malleshwaram            412
Marathahalli           1104
New BEL Road            389
Old Airport Road        216
Rajajinagar             305
Residency Road          247
Richmond Road           246
Sarjapur Road           724
Shanti Nagar            219
Shivajinagar            144
St. Marks Road          167
Ulsoor                  622
Whitefield             1119
others                 2890

------------------------------------------------------------------------------------
6. Create a pivot table showing the maximum rate for each combination of location and rest_type.

In [46]:
f = df.pivot_table(values='rate',index=['location','rest_type'],aggfunc='max')
f

                             rate
location rest_type
BTM      Bakery               4.1
         Cafe                 4.5
         Casual Dining        4.9
         Casual Dining, Bar   4.4
         Delivery             4.6
...                           ...
others   Delivery             4.4
         Dessert Parlor       4.8
         Quick Bites          4.5
         Takeaway, Delivery   4.5
         others               4.5

[357 rows x 1 columns]

----------------------------------------------------------------------
ex. Find the avg rating based on rest_type and location

In [42]:
d2=df.pivot_table(index=['location','rest_type'],values='rate',aggfunc='mean')
d2

                                 rate
location rest_type
BTM      Bakery              3.718481
         Cafe                3.648987
         Casual Dining       3.623080
         Casual Dining, Bar  4.263643
         Delivery            3.575627
...                               ...
others   Delivery            3.613168
         Dessert Parlor      3.716718
         Quick Bites         3.554804
         Takeaway, Delivery  3.561753
         others              3.683133

[357 rows x 1 columns]